/** Engine public surface (SPEC §1 interpreter). */
export * from './mode'
export * from './registry'
export * from './engine'
export * from './query'
export * from './logic'
export * from './instrument'
export * from './moduleEval'
export * from './dispatcher'
export * from './lifecycle'
export * from './customComponents'
export * from './roles'
export * from './ctx'
export * from './host'

export { default as EngineProvider } from './EngineProvider.vue'
export { default as PageRenderer } from './PageRenderer.vue'
export { default as BlockRenderer } from './BlockRenderer.vue'
export { default as BlockErrorBoundary } from './BlockErrorBoundary.vue'
